"""
src/ui/export.py
-----------------
Builds a formatted Word (.docx) document from the session chat history.
Uses python-docx (already in requirements as python-docx==1.1.2).

FIELD NAME NOTE:
    Messages in st.session_state.messages use:
        role:       "user" | "assistant"
        content:    str  (the question text for user, answer text for assistant)
        confidence: str  ("High", "Medium", "Low")  — assistant only

    Sources are stored separately in st.session_state.sources as a dict
    keyed by message index — they are passed in paired with each answer.
"""

import io
from datetime import datetime
import docx
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def build_session_docx(messages: list[dict], sources: dict | None = None) -> bytes:
    """
    Build a .docx file from the chat session history.

    Args:
        messages: List of message dicts from st.session_state.messages.
                  Each dict has: role ("user"|"assistant"), content (str),
                  and optionally confidence (str) for assistant messages.
        sources:  st.session_state.sources dict keyed by message index.
                  Each value is a list of chunk dicts with "citation" key.
                  Pass None to omit sources from the export.

    Returns:
        Raw bytes suitable for st.download_button.
    """
    if sources is None:
        sources = {}

    doc = docx.Document()

    # ── Title ──
    title = doc.add_heading("Police Oversight CRAG Research Session", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # ── Date ──
    date_para = doc.add_paragraph(
        f"Ontario Police Oversight — AI Legislative QA\n"
        f"Exported: {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    )
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph()  # spacer

    doc.add_paragraph("─" * 60)
    doc.add_paragraph()

    # ── Q&A pairs — walk messages in user/assistant pairs ──
    qa_num = 0
    i = 0
    while i < len(messages):
        msg = messages[i]

        # Collect the user question
        if msg.get("role") == "user":
            question = msg.get("content", "")
            answer = ""
            confidence = "Low"
            msg_sources = []

            # Look for the paired assistant reply immediately after
            if i + 1 < len(messages) and messages[i + 1].get("role") == "assistant":
                asst = messages[i + 1]
                answer = asst.get("content", "")
                confidence = asst.get("confidence", "Low")
                # Sources are keyed by the assistant message index
                msg_sources = sources.get(i + 1, [])
                i += 2  # consume both messages
            else:
                i += 1  # user message with no reply yet

            qa_num += 1

            # Question heading
            doc.add_heading(f"Q{qa_num}: {question}", level=2)

            # Confidence label
            symbol = {"High": "● HIGH", "Medium": "◑ MEDIUM", "Low": "○ LOW"}.get(
                confidence, confidence
            )
            conf_para = doc.add_paragraph(f"Confidence: {symbol}")
            conf_para.runs[0].italic = True

            doc.add_paragraph()  # spacer

            # Answer
            if answer:
                doc.add_paragraph(answer)

            # Sources
            if msg_sources:
                doc.add_paragraph("Sources:", style="Intense Quote")
                for src in msg_sources:
                    citation = src.get("citation", src.get("section_title", "Unknown"))
                    doc.add_paragraph(citation, style="List Bullet")

            doc.add_paragraph()
            doc.add_paragraph("─" * 60)
            doc.add_paragraph()

        else:
            # Orphaned assistant message (shouldn't happen normally)
            i += 1

    # ── Footer ──
    footer_para = doc.add_paragraph(
        "Generated by Police Oversight CRAG — Agentic Legislative Analysis\n"
        "Legal AI Engineering Portfolio | Corrective RAG Pipeline"
    )
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Return as bytes
    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
